KthWsnLongrangeRadioUplink: ax25.c File Reference
ax25.c File Reference
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "ax25.h"
Defines
#define INITFCS 0xffff
Functions
void ax25_initialize_network (uint8_t *myCallsign)
uint8_t * ax25_get_local_callsign (uint8_t *callsign_out)
uint8_t * ax25_get_broadcast_callsign (uint8_t *callsign_out)
uint32_t ax25_create_ui_packet (uint8_t *src_in, uint8_t *dst_in, uint8_t *payload_in, uint16_t payload_length, uint8_t *packet_out)
uint8_t ax25_check_destination (uint8_t *my_dst, uint8_t *packet_dst_out, uint8_t *packet_in)
uint16_t ax25_open_ui_packet (uint8_t *src_out, uint8_t *dst_out, uint8_t *payload_out, uint8_t *packet_in, uint16_t packet_length)
Define Documentation
#define INITFCS 0xffff
Definition at line 18 of file ax25.c.
Function Documentation
uint8_t ax25_check_destination (uint8_t * my_dst, uint8_t * packet_dst_out, uint8_t * packet_in)
ax25_check_destination() checks the destination of the packet_in with my_dst if packet_dst is not null pointer writes the packet's destination to packet_dst returns zero if the addresses match
Definition at line 142 of file ax25.c.
References AX25_DESTINATION_LENGTH, and AX25_DESTINATION_OFFSET.
uint32_t ax25_create_ui_packet (uint8_t * src_in, uint8_t * dst_in, uint8_t * payload_in, uint16_t payload_length, uint8_t * packet_out)
ax25_create_packet() prepares an ax25 packet with source address, target destination address and payload and puts it in packet_out also computes the checksum and also puts it into the packet on successful encapsulation function returns the length of the packet else returns zero
Definition at line 102 of file ax25.c.
References AX25_CONTROL_LENGTH, AX25_CONTROL_OFFSET, AX25_CONTROL_UI_FINAL, AX25_DESTINATION_LENGTH, AX25_DESTINATION_OFFSET, AX25_FCS_LENGTH, AX25_MAX_PAYLOAD_LENGTH, AX25_PAYLOAD_OFFSET, AX25_PID_LENGTH, AX25_PID_NO_PROTOCOL, AX25_PID_OFFSET, AX25_SOURCE_LENGTH, and AX25_SOURCE_OFFSET.
Referenced by queueSerialData().
uint8_t* ax25_get_broadcast_callsign (uint8_t * callsign_out)
ax25_get_broadcast_callsign() return a pointer to the static broadcast address also if the parameter is not NULL, copies the callsign to parameter pointer
Definition at line 90 of file ax25.c.
Referenced by queueSerialData().
uint8_t* ax25_get_local_callsign (uint8_t * callsign_out)
ax25_get_local_address() return a pointer to the static local address also if the parameter is not NULL, copies the callsign to parameter pointer
Definition at line 78 of file ax25.c.
Referenced by main(), and queueSerialData().
void ax25_initialize_network (uint8_t * myCallsign)
ax25_initialize_network() copies the ax25 callsign to static local eth address
Definition at line 72 of file ax25.c.
Referenced by main().
uint16_t ax25_open_ui_packet (uint8_t * src_out, uint8_t * dst_out, uint8_t * payload_out, uint8_t * packet_in, uint16_t packet_length)
ax25_open_packet() opens the packet_in and writes source address to src_out, destination address to dst_out writes the payload to payload_out before writing anything it first checks the checksum, if the checksum doesn't match, null is written to all pointers and function returns 0 on a successful opening function returns the length of the packet
Definition at line 158 of file ax25.c.
References AX25_CONTROL_LENGTH, AX25_CONTROL_OFFSET, AX25_DESTINATION_LENGTH, AX25_DESTINATION_OFFSET, AX25_FCS_LENGTH, AX25_FCS_OFFSET, AX25_PAYLOAD_OFFSET, AX25_PID_LENGTH, AX25_PID_OFFSET, AX25_SOURCE_LENGTH, and AX25_SOURCE_OFFSET.
Referenced by main().