KthWsnLongrangeRadioUplink: devtag-allinone.c File Reference
devtag-allinone.c File Reference
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <libgen.h>
#include <stdlib.h>
#include <ctype.h>
#include <fnmatch.h>
#include "devtag-allinone.h"
Defines
#define DEVTAG_ALLINONE
Functions
int devtag_usb_scan (struct dev_head *result, const struct devinfo_head *sel)
int devtag_dev_scan (struct dev_head *result, const struct devinfo_head *sel)
int devtag_lookup2 (char *buf, size_t bufsize, char *constbuf, size_t constsize, const char *devname)
int devtag_lookup (char *buf, size_t bufsize, const char *devname)
char * devtag_get (const char *devname)
Define Documentation
#define DEVTAG_ALLINONE
Definition at line 1 of file devtag-allinone.c.
Function Documentation
int devtag_dev_scan (struct dev_head * result, const struct devinfo_head * sel)
Definition at line 259 of file devtag-allinone.c.
References devtag_usb_scan().
char* devtag_get (const char * devname)
Definition at line 440 of file devtag-allinone.c.
References devtag_lookup().
Referenced by main().
int devtag_lookup (char * buf, size_t bufsize, const char * devname)
Definition at line 435 of file devtag-allinone.c.
References devtag_lookup2().
Referenced by devtag_get().
int devtag_lookup2 (char * buf, size_t bufsize, char * constbuf, size_t constsize, const char * devname)
Definition at line 373 of file devtag-allinone.c.
References devname::devname, dev::devnames, devtag_usb_scan(), devname_head::head, dev_head::head, devinfo_head::head, and dev::next.
Referenced by devtag_lookup().
int devtag_usb_scan (struct dev_head * result, const struct devinfo_head * sel)
Definition at line 58 of file devtag-allinone.c.
Referenced by devtag_dev_scan(), and devtag_lookup2().