KthWsnLongrangeRadioUplink: Header Files/devtag-allinone.h File Reference
Header Files/devtag-allinone.h File Reference
#include <sys/types.h>
Classes
struct devname_head
struct devname
struct devinfo_head
struct devinfo
struct dev_head
struct dev
Defines
#define LIBDEVTAG_H
#define LIBDEVTAG_VERSION "1.0.6"
Functions
int devtag_lookup (char *buf, size_t bufsize, const char *devtag)
int devtag_lookup2 (char *buf, size_t bufsize, char *constbuf, size_t constsize, const char *devtag)
char * devtag_get (const char *devtag)
int devtag_dev_scan (struct dev_head *result, const struct devinfo_head *sel)
int devtag_usb_scan (struct dev_head *result, const struct devinfo_head *sel)
Define Documentation
#define LIBDEVTAG_H
Definition at line 29 of file devtag-allinone.h.
#define LIBDEVTAG_VERSION "1.0.6"
Definition at line 31 of file devtag-allinone.h.
Function Documentation
int devtag_dev_scan (struct dev_head * result, const struct devinfo_head * sel)
Definition at line 259 of file devtag-allinone.c.
References devtag_usb_scan().
char* devtag_get (const char * devtag)
Definition at line 440 of file devtag-allinone.c.
References devtag_lookup().
Referenced by main().
int devtag_lookup (char * buf, size_t bufsize, const char * devtag)
Definition at line 435 of file devtag-allinone.c.
References devtag_lookup2().
Referenced by devtag_get().
int devtag_lookup2 (char * buf, size_t bufsize, char * constbuf, size_t constsize, const char * devtag)
Definition at line 373 of file devtag-allinone.c.
References devname::devname, dev::devnames, devtag_usb_scan(), devname_head::head, dev_head::head, devinfo_head::head, and dev::next.
Referenced by devtag_lookup().
int devtag_usb_scan (struct dev_head * result, const struct devinfo_head * sel)
Definition at line 58 of file devtag-allinone.c.
Referenced by devtag_dev_scan(), and devtag_lookup2().