KthWsnLongrangeRadioUplink: ethernet.c File Reference
ethernet.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include "ethernet.h"
Functions
void eth_initialize_network (uint8_t *myEth)
uint8_t * eth_get_local_address (uint8_t *eth_out)
uint8_t * eth_get_broadcast_address (uint8_t *eth_out)
uint32_t eth_create_packet (uint8_t *src_in, uint8_t *dst_in, uint8_t *payload_in, uint16_t payload_length, uint8_t *packet_out)
uint8_t eth_check_destination (uint8_t *my_dst, uint8_t *packet_dst, uint8_t *packet_in)
uint16_t eth_open_packet (uint8_t *src_out, uint8_t *dst_out, uint8_t *payload_out, uint8_t *packet_in, uint16_t packet_length)
Function Documentation
uint8_t eth_check_destination (uint8_t * my_dst, uint8_t * packet_dst, uint8_t * packet_in)
eth_check_destination() checks the destination of the packet_in with my_dst if packet_dst is not null pointer writes the packet's destination to packet_dst returns zero if the addresses match
Definition at line 118 of file ethernet.c.
References ETH_DESTINATION_LENGTH, and ETH_DESTINATION_OFFSET.
uint32_t eth_create_packet (uint8_t * src_in, uint8_t * dst_in, uint8_t * payload_in, uint16_t payload_length, uint8_t * packet_out)
eth_create_packet() prepares an ethernet packet with source address, target destination address and payload and puts it in packet_out also computes the checksum and also puts it into the packet on successful encapsulation function returns the length of the packet else returns zero
Definition at line 73 of file ethernet.c.
References ETH_DESTINATION_LENGTH, ETH_DESTINATION_OFFSET, ETH_FCS_LENGTH, ETH_LENGTH_LENGTH, ETH_MAX_PAYLOAD_LENGTH, ETH_PAYLOAD_OFFSET, ETH_SOURCE_LENGTH, and ETH_SOURCE_OFFSET.
Referenced by queueSerialData().
uint8_t* eth_get_broadcast_address (uint8_t * eth_out)
eth_get_broadcast_address() return a pointer to the static broadcast address also if the parameter is not NULL, copies the address to parameter pointer
Definition at line 52 of file ethernet.c.
Referenced by queueSerialData().
uint8_t* eth_get_local_address (uint8_t * eth_out)
eth_get_local_address() return a pointer to the static local address also if the parameter is not NULL, copies the address to parameter pointer
Definition at line 40 of file ethernet.c.
Referenced by main(), and queueSerialData().
void eth_initialize_network (uint8_t * myEth)
eth_initialize_network() copies the ethernet address to static local eth address
Definition at line 33 of file ethernet.c.
Referenced by main().
uint16_t eth_open_packet (uint8_t * src_out, uint8_t * dst_out, uint8_t * payload_out, uint8_t * packet_in, uint16_t packet_length)
eth_open_packet() opens the packet_in and writes source address to src_out, destination address to dst_out writes the payload to payload_out before writing anything it first checks the checksum, if the checksum doesn't match, null is written to all pointers and function returns 0 on a successful opening function returns the length of the packet
Definition at line 141 of file ethernet.c.
References ETH_DESTINATION_LENGTH, ETH_DESTINATION_OFFSET, ETH_FCS_LENGTH, ETH_LENGTH_LENGTH, ETH_LENGTH_OFFSET, ETH_PAYLOAD_OFFSET, ETH_SOURCE_LENGTH, and ETH_SOURCE_OFFSET.
Referenced by main().