KthWsnLongrangeRadioUplink: Header Files/lock.h File Reference
Header Files/lock.h File Reference
Functions
char * mbasename (char *s, char *res, int reslen)
int lockfile_create (void)
void lockfile_remove (void)
int have_lock_dir (char *dial_tty)
int get_lock (char *dial_tty)
int getLockRetries (void)
int decrementLockRetries (void)
Function Documentation
int decrementLockRetries (void)
Definition at line 29 of file lock.c.
Referenced by main().
int get_lock (char * dial_tty)
Definition at line 113 of file lock.c.
References buf, have_lock_dir(), and lockfile_create().
Referenced by main().
int getLockRetries (void)
Definition at line 25 of file lock.c.
int have_lock_dir (char * dial_tty)
Definition at line 93 of file lock.c.
References buf, mbasename(), and P_LOCK.
Referenced by get_lock().
int lockfile_create (void)
Definition at line 61 of file lock.c.
References buf.
Referenced by get_lock().
void lockfile_remove (void)
Definition at line 87 of file lock.c.
Referenced by safe_exit().
char* mbasename (char * s, char * res, int reslen)
Definition at line 35 of file lock.c.
Referenced by have_lock_dir().