KthWsnLongrangeRadioUplink: Header Files/manchester.h File Reference
Header Files/manchester.h File Reference
#include <inttypes.h>
#include <stdint.h>
Functions
uint16_t manchester_encode (uint8_t *input, uint8_t *output, uint16_t size)
uint16_t manchester_decode (uint8_t *input, uint8_t *output, uint16_t size)
uint8_t isManchester_encoded (uint8_t)
Function Documentation
uint8_t isManchester_encoded (uint8_t) [inline]
Definition at line 139 of file manchester.c.
Referenced by main().
uint16_t manchester_decode (uint8_t * input, uint8_t * output, uint16_t size)
Definition at line 155 of file manchester.c.
Referenced by main().
uint16_t manchester_encode (uint8_t * input, uint8_t * output, uint16_t size)
Definition at line 144 of file manchester.c.
Referenced by queueSerialData().