KthWsnLongrangeRadioUplink: Header Files/radiotftp.h File Reference
Header Files/radiotftp.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <termio.h>
#include <time.h>
#include <sys/fcntl.h>
#include <fcntl.h>
#include <string.h>
#include <signal.h>
#include <inttypes.h>
#include <sys/time.h>
#include <sys/select.h>
#include <stdint.h>
#include "lock.h"
#include "ethernet.h"
#include "udp_ip.h"
#include "timers.h"
#include "lock.h"
#include "devtag-allinone.h"
#include "manchester.h"
#include "tftp.h"
#include "ax25.h"
Defines
#define TEMPFILE_PREFIX "linefeed\0"
#define TEMPFILE_POSTFIX ".txt\0"
#define RADIOTFTP_COMMAND_PUT "put"
#define RADIOTFTP_COMMAND_GET "get"
#define RADIOTFTP_COMMAND_APPEND_FILE "appendfile"
#define RADIOTFTP_COMMAND_APPEND_LINE "appendline"
#define RADIOTFTP_COMMAND_BEACON "beacon"
Functions
uint8_t setRTS (uint8_t level)
TIMER_HANDLER_FUNCTION_PROTO (idle_timer_handler)
void safe_exit (int retVal)
void sigINT_handler (int sig)
void sigIO_handler (int status)
void sigRTALRM_handler (int sig)
uint8_t queueSerialData (uint8_t *src, uint16_t src_port, uint8_t *dst, uint16_t dst_port, uint8_t *dataptr, uint16_t datalen)
uint16_t transmitSerialData (void)
uint8_t udp_packet_demultiplexer (uint8_t *src, uint16_t src_port, uint8_t *dst, uint16_t dst_port, uint8_t *payload, uint16_t len)
int main (int ac, char *av[])
Define Documentation
#define RADIOTFTP_COMMAND_APPEND_FILE "appendfile"
Definition at line 46 of file radiotftp.h.
Referenced by main().
#define RADIOTFTP_COMMAND_APPEND_LINE "appendline"
Definition at line 47 of file radiotftp.h.
Referenced by main().
#define RADIOTFTP_COMMAND_BEACON "beacon"
Definition at line 48 of file radiotftp.h.
Referenced by main().
#define RADIOTFTP_COMMAND_GET "get"
Definition at line 45 of file radiotftp.h.
Referenced by main().
#define RADIOTFTP_COMMAND_PUT "put"
Definition at line 44 of file radiotftp.h.
Referenced by main().
#define TEMPFILE_POSTFIX ".txt\0"
Definition at line 43 of file radiotftp.h.
Referenced by main().
#define TEMPFILE_PREFIX "linefeed\0"
Definition at line 42 of file radiotftp.h.
Referenced by main().
Function Documentation
int main (int ac, char * av[])
convert text ip to numerical
read settings from radiotftp.conf file
Definition at line 379 of file radiotftp.c.
References ax25_get_local_callsign(), ax25_initialize_network(), ax25_open_ui_packet(), background, baud, buf, command_buffer, createTempFile(), decrementLockRetries(), devtag_get(), dial_tty, END_OF_FILE, eth_get_local_address(), eth_initialize_network(), eth_open_packet(), get_lock(), HELLO_WORLD_PORT, idle_flag, io, IO_BUFSIZE, io_flag, io_index, isManchester_encoded(), manchester_buffer, manchester_decode(), my_ip_address, old, print_addr_dec(), print_addr_hex(), print_callsign(), queue_flag, queueSerialData(), RADIOTFTP_COMMAND_APPEND_FILE, RADIOTFTP_COMMAND_APPEND_LINE, RADIOTFTP_COMMAND_BEACON, RADIOTFTP_COMMAND_GET, RADIOTFTP_COMMAND_PUT, readnline(), restore, sa_io, safe_exit(), serialportFd, sigIO_handler(), sigRTALRM_handler(), SYNC_LENGTH, syncword, tempFile, TEMPFILE_POSTFIX, TEMPFILE_PREFIX, tempFileName, text_to_ip(), tftp_initialize(), TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, tftp_sendRequest(), tftp_sendSingleBlockData(), timer_flag, timers_initialize(), transmitSerialData(), udp_buffer, udp_dst, udp_dst_prt, udp_get_broadcast_ip(), udp_get_data_queuer_fptr(), udp_get_localhost_ip(), udp_initialize_ip_network(), udp_open_packet(), udp_packet_demultiplexer(), udp_src, udp_src_prt, and usage().
uint8_t queueSerialData (uint8_t * src, uint16_t src_port, uint8_t * dst, uint16_t dst_port, uint8_t * dataptr, uint16_t datalen)
Definition at line 199 of file radiotftp.c.
References ax25_create_ui_packet(), ax25_get_broadcast_callsign(), ax25_get_local_callsign(), END_OF_FILE, eth_create_packet(), eth_get_broadcast_address(), eth_get_local_address(), manchester_buffer, manchester_encode(), preamble, PREAMBLE_LENGTH, queue_flag, SYNC_LENGTH, syncword, transmit_buffer, transmit_length, udp_buffer, and udp_create_packet().
Referenced by main().
void safe_exit (int retVal)
Definition at line 162 of file radiotftp.c.
References deleteTempFile(), lockfile_remove(), old, restore, and serialportFd.
Referenced by main(), PACKET_HANDLER_FUNCTION(), sigINT_handler(), tftp_sendRequest(), tftp_sendSingleBlockData(), TIMER_HANDLER_FUNCTION(), and usage().
uint8_t setRTS (uint8_t level)
Definition at line 132 of file radiotftp.c.
References serialportFd.
Referenced by transmitSerialData().
void sigINT_handler (int sig)
Definition at line 178 of file radiotftp.c.
References safe_exit().
void sigIO_handler (int status)
Definition at line 185 of file radiotftp.c.
References io_flag, and signalCount.
Referenced by main().
void sigRTALRM_handler (int sig)
Definition at line 192 of file radiotftp.c.
References timer_flag.
Referenced by main().
TIMER_HANDLER_FUNCTION_PROTO (idle_timer_handler)
uint16_t transmitSerialData (void)
Definition at line 257 of file radiotftp.c.
References BYTE_ERROR_PROB, serialportFd, setRTS(), transmit_buffer, and transmit_length.
Referenced by main().
uint8_t udp_packet_demultiplexer (uint8_t * src, uint16_t src_port, uint8_t * dst, uint16_t dst_port, uint8_t * payload, uint16_t len)
Definition at line 328 of file radiotftp.c.
References HELLO_WORLD_PORT, IPV6_DESTINATION_LENGTH, print_addr_dec(), tftp_transfer_src_port(), udp_get_broadcast_ip(), and udp_get_localhost_ip().
Referenced by main().