KthWsnLongrangeRadioUplink: radiotftp.c File Reference
radiotftp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <termio.h>
#include <time.h>
#include <sys/fcntl.h>
#include <fcntl.h>
#include <string.h>
#include <signal.h>
#include <inttypes.h>
#include <sys/time.h>
#include <sys/select.h>
#include <stdint.h>
#include "lock.h"
#include "devtag-allinone.h"
#include "manchester.h"
#include "ethernet.h"
#include "udp_ip.h"
#include "tftp.h"
#include "timers.h"
#include "radiotftp.h"
#include "ax25.h"
#include "util.h"
Defines
#define END_OF_FILE 28
#define CTRLD 4
#define P_LOCK "/var/lock"
#define IO_DRIVEN 0
#define HELLO_WORLD_PORT 12345
#define PREAMBLE_LENGTH 10
#define SYNC_LENGTH 4
#define BYTE_ERROR_PROB 0
#define IO_BUFSIZE 255
Functions
int createTempFile (char *prefix, char *postfix)
int deleteTempFile ()
uint8_t setRTS (uint8_t level)
TIMER_HANDLER_FUNCTION (idle_timer_handler)
void safe_exit (int retVal)
void sigINT_handler (int sig)
void sigIO_handler (int status)
void sigRTALRM_handler (int sig)
uint8_t queueSerialData (uint8_t *src, uint16_t src_port, uint8_t *dst, uint16_t dst_port, uint8_t *dataptr, uint16_t datalen)
uint16_t transmitSerialData (void)
uint8_t udp_packet_demultiplexer (uint8_t *src, uint16_t src_port, uint8_t *dst, uint16_t dst_port, uint8_t *payload, uint16_t len)
int main (int ac, char *av[])
Variables
FILE * tempFile
char tempFileName [64]
char dial_tty [128]
const uint8_t my_ip_address [6]
unsigned char preamble [PREAMBLE_LENGTH]
unsigned char syncword [SYNC_LENGTH]
uint8_t command_buffer [256]
uint8_t manchester_buffer [(UDP_MAX_PAYLOAD_LENGTH+UDP_TOTAL_HEADERS_LENGTH)*2]
uint8_t transmit_buffer [sizeof(manchester_buffer)+PREAMBLE_LENGTH+SYNC_LENGTH+2]
uint8_t udp_buffer [UDP_MAX_PAYLOAD_LENGTH+20]
uint16_t transmit_length = 0
uint8_t io_index = 0
uint8_t io [IO_BUFSIZE]
uint8_t buf [sizeof(manchester_buffer)+PREAMBLE_LENGTH+SYNC_LENGTH+2]
int background = 0
long baud = B4800
struct termios tp old
struct sigaction sa_io
struct sigaction sa_alarm
int serialportFd
int restore = 0
volatile uint8_t io_flag = 0
volatile uint8_t alarm_flag = 0
volatile uint8_t timer_flag = 0
volatile uint8_t queue_flag = 0
volatile uint8_t idle_flag = 0
uint8_t eth_src [6]
uint8_t eth_dst [6]
uint8_t udp_src [6]
uint8_t udp_dst [6]
uint16_t udp_src_prt
uint16_t udp_dst_prt
uint64_t signalCount = 0
Define Documentation
#define BYTE_ERROR_PROB 0
Definition at line 58 of file radiotftp.c.
Referenced by transmitSerialData().
#define CTRLD 4
Definition at line 37 of file radiotftp.c.
#define END_OF_FILE 28
Definition at line 36 of file radiotftp.c.
Referenced by main(), and queueSerialData().
#define HELLO_WORLD_PORT 12345
Definition at line 41 of file radiotftp.c.
Referenced by main(), and udp_packet_demultiplexer().
#define IO_BUFSIZE 255
Definition at line 78 of file radiotftp.c.
Referenced by main().
#define IO_DRIVEN 0
Definition at line 40 of file radiotftp.c.
#define P_LOCK "/var/lock"
Definition at line 38 of file radiotftp.c.
#define PREAMBLE_LENGTH 10
Definition at line 50 of file radiotftp.c.
Referenced by queueSerialData().
#define SYNC_LENGTH 4
Definition at line 54 of file radiotftp.c.
Referenced by main(), and queueSerialData().
Function Documentation
int createTempFile (char * prefix, char * postfix)
Definition at line 111 of file radiotftp.c.
References GMT_OFFSET, tempFile, and tempFileName.
Referenced by main().
int deleteTempFile ()
Definition at line 120 of file radiotftp.c.
References tempFile, and tempFileName.
Referenced by safe_exit().
int main (int ac, char * av[])
convert text ip to numerical
read settings from radiotftp.conf file
Definition at line 379 of file radiotftp.c.
References ax25_get_local_callsign(), ax25_initialize_network(), ax25_open_ui_packet(), background, baud, buf, command_buffer, createTempFile(), decrementLockRetries(), devtag_get(), dial_tty, END_OF_FILE, eth_get_local_address(), eth_initialize_network(), eth_open_packet(), get_lock(), HELLO_WORLD_PORT, idle_flag, io, IO_BUFSIZE, io_flag, io_index, isManchester_encoded(), manchester_buffer, manchester_decode(), my_ip_address, old, print_addr_dec(), print_addr_hex(), print_callsign(), queue_flag, queueSerialData(), RADIOTFTP_COMMAND_APPEND_FILE, RADIOTFTP_COMMAND_APPEND_LINE, RADIOTFTP_COMMAND_BEACON, RADIOTFTP_COMMAND_GET, RADIOTFTP_COMMAND_PUT, readnline(), restore, sa_io, safe_exit(), serialportFd, sigIO_handler(), sigRTALRM_handler(), SYNC_LENGTH, syncword, tempFile, TEMPFILE_POSTFIX, TEMPFILE_PREFIX, tempFileName, text_to_ip(), tftp_initialize(), TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, tftp_sendRequest(), tftp_sendSingleBlockData(), timer_flag, timers_initialize(), transmitSerialData(), udp_buffer, udp_dst, udp_dst_prt, udp_get_broadcast_ip(), udp_get_data_queuer_fptr(), udp_get_localhost_ip(), udp_initialize_ip_network(), udp_open_packet(), udp_packet_demultiplexer(), udp_src, udp_src_prt, and usage().
uint8_t queueSerialData (uint8_t * src, uint16_t src_port, uint8_t * dst, uint16_t dst_port, uint8_t * dataptr, uint16_t datalen)
Definition at line 199 of file radiotftp.c.
References ax25_create_ui_packet(), ax25_get_broadcast_callsign(), ax25_get_local_callsign(), END_OF_FILE, eth_create_packet(), eth_get_broadcast_address(), eth_get_local_address(), manchester_buffer, manchester_encode(), preamble, PREAMBLE_LENGTH, queue_flag, SYNC_LENGTH, syncword, transmit_buffer, transmit_length, udp_buffer, and udp_create_packet().
Referenced by main().
void safe_exit (int retVal)
Definition at line 162 of file radiotftp.c.
References deleteTempFile(), lockfile_remove(), old, restore, and serialportFd.
Referenced by main(), PACKET_HANDLER_FUNCTION(), sigINT_handler(), tftp_sendRequest(), tftp_sendSingleBlockData(), TIMER_HANDLER_FUNCTION(), and usage().
uint8_t setRTS (uint8_t level)
Definition at line 132 of file radiotftp.c.
References serialportFd.
Referenced by transmitSerialData().
void sigINT_handler (int sig)
Definition at line 178 of file radiotftp.c.
References safe_exit().
void sigIO_handler (int status)
Definition at line 185 of file radiotftp.c.
References io_flag, and signalCount.
Referenced by main().
void sigRTALRM_handler (int sig)
Definition at line 192 of file radiotftp.c.
References timer_flag.
Referenced by main().
TIMER_HANDLER_FUNCTION (idle_timer_handler)
Definition at line 155 of file radiotftp.c.
References idle_flag.
uint16_t transmitSerialData (void)
Definition at line 257 of file radiotftp.c.
References BYTE_ERROR_PROB, serialportFd, setRTS(), transmit_buffer, and transmit_length.
Referenced by main().
uint8_t udp_packet_demultiplexer (uint8_t * src, uint16_t src_port, uint8_t * dst, uint16_t dst_port, uint8_t * payload, uint16_t len)
Definition at line 328 of file radiotftp.c.
References HELLO_WORLD_PORT, IPV6_DESTINATION_LENGTH, print_addr_dec(), tftp_transfer_src_port(), udp_get_broadcast_ip(), and udp_get_localhost_ip().
Referenced by main().
Variable Documentation
volatile uint8_t alarm_flag = 0
Definition at line 94 of file radiotftp.c.
int background = 0
Definition at line 84 of file radiotftp.c.
Referenced by main().
long baud = B4800
Definition at line 85 of file radiotftp.c.
Referenced by main().
uint8_t buf[sizeof(manchester_buffer)+PREAMBLE_LENGTH+SYNC_LENGTH+2]
Definition at line 81 of file radiotftp.c.
Referenced by get_lock(), have_lock_dir(), lockfile_create(), and main().
uint8_t command_buffer[256]
Definition at line 60 of file radiotftp.c.
Referenced by main().
char dial_tty[128]
Definition at line 45 of file radiotftp.c.
Referenced by main().
uint8_t eth_dst[6]
Definition at line 99 of file radiotftp.c.
uint8_t eth_src[6]
Definition at line 99 of file radiotftp.c.
volatile uint8_t idle_flag = 0
Definition at line 97 of file radiotftp.c.
Referenced by main(), and TIMER_HANDLER_FUNCTION().
uint8_t io[IO_BUFSIZE]
Definition at line 80 of file radiotftp.c.
Referenced by main().
volatile uint8_t io_flag = 0
Definition at line 93 of file radiotftp.c.
Referenced by main(), and sigIO_handler().
uint8_t io_index = 0
Definition at line 79 of file radiotftp.c.
Referenced by main().
uint8_t manchester_buffer[(UDP_MAX_PAYLOAD_LENGTH+UDP_TOTAL_HEADERS_LENGTH)*2]
Definition at line 71 of file radiotftp.c.
Referenced by main(), and queueSerialData().
const uint8_t my_ip_address[6]
Initial value:
{ 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6 }
Definition at line 47 of file radiotftp.c.
Referenced by main().
struct termios tp old
Definition at line 87 of file radiotftp.c.
Referenced by main(), and safe_exit().
unsigned char preamble[PREAMBLE_LENGTH]
Initial value:
{ 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55 }
Definition at line 51 of file radiotftp.c.
Referenced by queueSerialData().
volatile uint8_t queue_flag = 0
Definition at line 96 of file radiotftp.c.
Referenced by main(), and queueSerialData().
int restore = 0
Definition at line 92 of file radiotftp.c.
Referenced by main(), and safe_exit().
struct sigaction sa_alarm
Definition at line 89 of file radiotftp.c.
struct sigaction sa_io
Definition at line 88 of file radiotftp.c.
Referenced by main().
int serialportFd
Definition at line 91 of file radiotftp.c.
Referenced by main(), safe_exit(), setRTS(), and transmitSerialData().
uint64_t signalCount = 0
Definition at line 184 of file radiotftp.c.
Referenced by sigIO_handler().
unsigned char syncword[SYNC_LENGTH]
Initial value:
{ 0xAA, 0x55, 0xAA, 0x55 }
Definition at line 55 of file radiotftp.c.
Referenced by main(), and queueSerialData().
FILE* tempFile
Definition at line 43 of file radiotftp.c.
Referenced by createTempFile(), deleteTempFile(), and main().
char tempFileName[64]
Definition at line 44 of file radiotftp.c.
Referenced by createTempFile(), deleteTempFile(), and main().
volatile uint8_t timer_flag = 0
Definition at line 95 of file radiotftp.c.
Referenced by main(), and sigRTALRM_handler().
uint8_t transmit_buffer[sizeof(manchester_buffer)+PREAMBLE_LENGTH+SYNC_LENGTH+2]
Definition at line 73 of file radiotftp.c.
Referenced by queueSerialData(), and transmitSerialData().
uint16_t transmit_length = 0
Definition at line 75 of file radiotftp.c.
Referenced by queueSerialData(), and transmitSerialData().
uint8_t udp_buffer[UDP_MAX_PAYLOAD_LENGTH+20]
Definition at line 74 of file radiotftp.c.
Referenced by main(), and queueSerialData().
uint8_t udp_dst[6]
Definition at line 100 of file radiotftp.c.
Referenced by main().
uint16_t udp_dst_prt
Definition at line 101 of file radiotftp.c.
Referenced by main().
uint8_t udp_src[6]
Definition at line 100 of file radiotftp.c.
Referenced by main().
uint16_t udp_src_prt
Definition at line 101 of file radiotftp.c.
Referenced by main().