KthWsnLongrangeRadioUplink: tftp.c File Reference
tftp.c File Reference
#include <inttypes.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include "udp_ip.h"
#include "tftp.h"
#include "timers.h"
#include "radiotftp.h"
#include "util.h"
Functions
uint8_t tftp_initialize (dataQueuerfptr_t dataQueuer)
timer_t tftp_getTimerID (void)
void tftp_setStatus (uint8_t newStatus)
uint16_t tftp_transfer_src_port (void)
uint16_t tftp_transfer_dst_port (void)
uint8_t tftp_getRandomRetransmissionTime (void)
uint8_t tftp_sendSingleBlockData (uint8_t *dst_ip, uint8_t *data_ptr, uint16_t data_len, uint8_t *remote_filename)
uint8_t tftp_sendRequest (uint8_t opcode, uint8_t *dst_ip, uint8_t *local_filename, uint8_t *remote_filename, uint8_t remote_filename_len, uint8_t append)
uint8_t tftp_sendData (uint8_t *dst_ip, uint8_t blockNum)
uint8_t tftp_sendError (uint8_t type, uint8_t *dst_ip, uint16_t dst_prt, uint8_t *additionalInfo, uint8_t infoLen)
uint8_t tftp_sendAck (uint8_t *dst_ip, uint8_t blockNum)
PACKET_HANDLER_FUNCTION (tftp_negotiate)
PACKET_HANDLER_FUNCTION (tftp_transfer)
TIMER_HANDLER_FUNCTION (tftp_timer_handler)
Function Documentation
PACKET_HANDLER_FUNCTION (tftp_transfer)
Definition at line 519 of file tftp.c.
References message_t::blockNumber, message_t::opcode, safe_exit(), TFT_DATA_HEADER_SIZE, TFTP_COMPLETE_TIMEOUT, TFTP_ERROR_SEE_MESSAGE, TFTP_MAX_BLOCK_SIZE, TFTP_OPCODE_ACK, TFTP_OPCODE_DATA, TFTP_OPCODE_ERROR, TFTP_OPCODE_WRQ_SINGLE, TFTP_READ_TIMEOUT, tftp_sendAck(), tftp_sendData(), tftp_sendError(), TFTP_STATUS_IDLE, TFTP_STATUS_RECEIVING, TFTP_STATUS_SENDING, timers_cancel_timer(), and timers_create_timer().
PACKET_HANDLER_FUNCTION (tftp_negotiate)
Definition at line 327 of file tftp.c.
References print_time(), TFTP_ERROR_FILE_NOT_FOUND, TFTP_ERROR_ILLEGAL_OPERATION, TFTP_ERROR_SEE_MESSAGE, TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, TFTP_OPCODE_WRQ_SINGLE, tftp_sendAck(), tftp_sendData(), tftp_sendError(), tftp_setStatus(), TFTP_STATUS_IDLE, TFTP_STATUS_RECEIVING, and TFTP_STATUS_SENDING.
uint8_t tftp_getRandomRetransmissionTime (void)
Definition at line 57 of file tftp.c.
References TFTP_ACK_TIMEOUT_MAX, and TFTP_ACK_TIMEOUT_MIN.
Referenced by tftp_sendData(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
timer_t tftp_getTimerID (void)
Definition at line 40 of file tftp.c.
uint8_t tftp_initialize (dataQueuerfptr_t dataQueuer)
Definition at line 31 of file tftp.c.
References tftp_setStatus(), and TFTP_STATUS_IDLE.
Referenced by main().
uint8_t tftp_sendAck (uint8_t * dst_ip, uint8_t blockNum)
Definition at line 312 of file tftp.c.
References TFTP_OPCODE_ACK, and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendData (uint8_t * dst_ip, uint8_t blockNum)
Definition at line 255 of file tftp.c.
References message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, message_t::src, message_t::src_port, tftp_getRandomRetransmissionTime(), TFTP_MAX_BLOCK_SIZE, TFTP_OPCODE_DATA, timers_create_timer(), and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendError (uint8_t type, uint8_t * dst_ip, uint16_t dst_prt, uint8_t * additionalInfo, uint8_t infoLen)
Definition at line 285 of file tftp.c.
References message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, message_t::src, message_t::src_port, TFTP_OPCODE_ERROR, and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendRequest (uint8_t opcode, uint8_t * dst_ip, uint8_t * local_filename, uint8_t * remote_filename, uint8_t remote_filename_len, uint8_t append)
Definition at line 140 of file tftp.c.
References message_t::append, message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, print_addr_dec(), safe_exit(), message_t::src, message_t::src_port, tftp_getRandomRetransmissionTime(), TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, tftp_setStatus(), TFTP_STATUS_RECEIVING, TFTP_STATUS_SENDING, timers_create_timer(), and udp_get_localhost_ip().
Referenced by main().
uint8_t tftp_sendSingleBlockData (uint8_t * dst_ip, uint8_t * data_ptr, uint16_t data_len, uint8_t * remote_filename)
Definition at line 63 of file tftp.c.
References message_t::append, message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, print_addr_dec(), safe_exit(), message_t::src, message_t::src_port, TFTP_DEFAULT_FILENAME, TFTP_OPCODE_WRQ_SINGLE, TFTP_SINGLE_BLOCK_WAIT_TIME, timers_create_timer(), and udp_get_localhost_ip().
Referenced by main().
void tftp_setStatus (uint8_t newStatus)
Definition at line 45 of file tftp.c.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_initialize(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
uint16_t tftp_transfer_dst_port (void)
Definition at line 53 of file tftp.c.
uint16_t tftp_transfer_src_port (void)
Definition at line 49 of file tftp.c.
Referenced by udp_packet_demultiplexer().
TIMER_HANDLER_FUNCTION (tftp_timer_handler)
Definition at line 699 of file tftp.c.
References message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, safe_exit(), message_t::src_port, tftp_getRandomRetransmissionTime(), TFTP_MAX_TIMEOUTS, TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, TFTP_OPCODE_WRQ_SINGLE, tftp_setStatus(), TFTP_STATUS_IDLE, TFTP_STATUS_RECEIVING, TFTP_STATUS_SENDING, timers_create_timer(), and udp_get_localhost_ip().