KthWsnLongrangeRadioUplink: Header Files/tftp.h File Reference
Header Files/tftp.h File Reference
#include <inttypes.h>
#include <stdint.h>
#include "udp_ip.h"
#include "timers.h"
Classes
struct message_t
Defines
#define TFTP_STATUS_IDLE 0
#define TFTP_STATUS_SENDING 1
#define TFTP_STATUS_RECEIVING 2
#define TFTP_OPCODE_RRQ 0x0001
#define TFTP_OPCODE_WRQ 0x0002
#define TFTP_OPCODE_DATA 0x0003
#define TFTP_OPCODE_ACK 0x0004
#define TFTP_OPCODE_ERROR 0x0005
#define TFTP_OPCODE_WRQ_SINGLE 0x0006
#define TFTP_ERROR_SEE_MESSAGE 0x0000
#define TFTP_ERROR_FILE_NOT_FOUND 0x0001
#define TFTP_ERROR_ACCESS_VIOLATION 0x0002
#define TFTP_ERROR_DISK_FULL 0x0003
#define TFTP_ERROR_ILLEGAL_OPERATION 0x0004
#define TFTP_ERROR_UKNOWN_TID 0x0005
#define TFTP_ERROR_FILE_EXISTS 0x0006
#define TFTP_ERROR_NO_USER 0x0007
#define TFTP_MAX_BLOCK_SIZE 512
#define TFT_DATA_HEADER_SIZE 4
#define TFTP_SINGLE_BLOCK_WAIT_TIME 1
#define TFTP_ACK_TIMEOUT_MIN 5
#define TFTP_ACK_TIMEOUT_MAX 6
#define TFTP_READ_TIMEOUT 5
#define TFTP_COMPLETE_TIMEOUT 5
#define TFTP_MAX_TIMEOUTS 10
#define TFTP_DEFAULT_FILENAME "sensors.dat"
Functions
PACKET_HANDLER_FUNCTION_PROTO (tftp_negotiate)
PACKET_HANDLER_FUNCTION_PROTO (tftp_transfer)
TIMER_HANDLER_FUNCTION_PROTO (tftp_timer_handler)
uint8_t tftp_initialize (dataQueuerfptr_t dataQueuer)
uint8_t tftp_sendSingleBlockData (uint8_t *dst_ip, uint8_t *data_ptr, uint16_t data_len, uint8_t *remote_filename)
uint8_t tftp_sendRequest (uint8_t opcode, uint8_t *dst_ip, uint8_t *local_filename, uint8_t *remote_filename, uint8_t remote_filename_len, uint8_t append)
uint8_t tftp_sendData (uint8_t *dst_ip, uint8_t blockNum)
uint8_t tftp_sendError (uint8_t type, uint8_t *dst_ip, uint16_t dst_prt, uint8_t *additionalInfo, uint8_t infoLen)
uint8_t tftp_sendAck (uint8_t *dst_ip, uint8_t blockNum)
uint8_t tftp_getRandomRetransmissionTime (void)
void tftp_setStatus (uint8_t newStatus)
timer_t tftp_getTimerID (void)
uint16_t tftp_transfer_src_port (void)
uint16_t tftp_transfer_dst_port (void)
Define Documentation
#define TFT_DATA_HEADER_SIZE 4
Definition at line 42 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_ACK_TIMEOUT_MAX 6
Definition at line 46 of file tftp.h.
Referenced by tftp_getRandomRetransmissionTime().
#define TFTP_ACK_TIMEOUT_MIN 5
Definition at line 45 of file tftp.h.
Referenced by tftp_getRandomRetransmissionTime().
#define TFTP_COMPLETE_TIMEOUT 5
Definition at line 48 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_DEFAULT_FILENAME "sensors.dat"
Definition at line 51 of file tftp.h.
Referenced by tftp_sendSingleBlockData().
#define TFTP_ERROR_ACCESS_VIOLATION 0x0002
Definition at line 34 of file tftp.h.
#define TFTP_ERROR_DISK_FULL 0x0003
Definition at line 35 of file tftp.h.
#define TFTP_ERROR_FILE_EXISTS 0x0006
Definition at line 38 of file tftp.h.
#define TFTP_ERROR_FILE_NOT_FOUND 0x0001
Definition at line 33 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_ERROR_ILLEGAL_OPERATION 0x0004
Definition at line 36 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_ERROR_NO_USER 0x0007
Definition at line 39 of file tftp.h.
#define TFTP_ERROR_SEE_MESSAGE 0x0000
Definition at line 32 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_ERROR_UKNOWN_TID 0x0005
Definition at line 37 of file tftp.h.
#define TFTP_MAX_BLOCK_SIZE 512
Definition at line 41 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), and tftp_sendData().
#define TFTP_MAX_TIMEOUTS 10
Definition at line 49 of file tftp.h.
Referenced by TIMER_HANDLER_FUNCTION().
#define TFTP_OPCODE_ACK 0x0004
Definition at line 28 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), and tftp_sendAck().
#define TFTP_OPCODE_DATA 0x0003
Definition at line 27 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), and tftp_sendData().
#define TFTP_OPCODE_ERROR 0x0005
Definition at line 29 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), and tftp_sendError().
#define TFTP_OPCODE_RRQ 0x0001
Definition at line 25 of file tftp.h.
Referenced by main(), PACKET_HANDLER_FUNCTION(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
#define TFTP_OPCODE_WRQ 0x0002
Definition at line 26 of file tftp.h.
Referenced by main(), PACKET_HANDLER_FUNCTION(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
#define TFTP_OPCODE_WRQ_SINGLE 0x0006
Definition at line 30 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_sendSingleBlockData(), and TIMER_HANDLER_FUNCTION().
#define TFTP_READ_TIMEOUT 5
Definition at line 47 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION().
#define TFTP_SINGLE_BLOCK_WAIT_TIME 1
Definition at line 44 of file tftp.h.
Referenced by tftp_sendSingleBlockData().
#define TFTP_STATUS_IDLE 0
Definition at line 21 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_initialize(), and TIMER_HANDLER_FUNCTION().
#define TFTP_STATUS_RECEIVING 2
Definition at line 23 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
#define TFTP_STATUS_SENDING 1
Definition at line 22 of file tftp.h.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
Function Documentation
PACKET_HANDLER_FUNCTION_PROTO (tftp_transfer)
PACKET_HANDLER_FUNCTION_PROTO (tftp_negotiate)
uint8_t tftp_getRandomRetransmissionTime (void)
Definition at line 57 of file tftp.c.
References TFTP_ACK_TIMEOUT_MAX, and TFTP_ACK_TIMEOUT_MIN.
Referenced by tftp_sendData(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
timer_t tftp_getTimerID (void)
Definition at line 40 of file tftp.c.
uint8_t tftp_initialize (dataQueuerfptr_t dataQueuer)
Definition at line 31 of file tftp.c.
References tftp_setStatus(), and TFTP_STATUS_IDLE.
Referenced by main().
uint8_t tftp_sendAck (uint8_t * dst_ip, uint8_t blockNum)
Definition at line 312 of file tftp.c.
References TFTP_OPCODE_ACK, and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendData (uint8_t * dst_ip, uint8_t blockNum)
Definition at line 255 of file tftp.c.
References message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, message_t::src, message_t::src_port, tftp_getRandomRetransmissionTime(), TFTP_MAX_BLOCK_SIZE, TFTP_OPCODE_DATA, timers_create_timer(), and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendError (uint8_t type, uint8_t * dst_ip, uint16_t dst_prt, uint8_t * additionalInfo, uint8_t infoLen)
Definition at line 285 of file tftp.c.
References message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, message_t::src, message_t::src_port, TFTP_OPCODE_ERROR, and udp_get_localhost_ip().
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t tftp_sendRequest (uint8_t opcode, uint8_t * dst_ip, uint8_t * local_filename, uint8_t * remote_filename, uint8_t remote_filename_len, uint8_t append)
Definition at line 140 of file tftp.c.
References message_t::append, message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, print_addr_dec(), safe_exit(), message_t::src, message_t::src_port, tftp_getRandomRetransmissionTime(), TFTP_OPCODE_RRQ, TFTP_OPCODE_WRQ, tftp_setStatus(), TFTP_STATUS_RECEIVING, TFTP_STATUS_SENDING, timers_create_timer(), and udp_get_localhost_ip().
Referenced by main().
uint8_t tftp_sendSingleBlockData (uint8_t * dst_ip, uint8_t * data_ptr, uint16_t data_len, uint8_t * remote_filename)
Definition at line 63 of file tftp.c.
References message_t::append, message_t::blockNumber, message_t::dst, message_t::dst_port, message_t::opcode, message_t::payload, message_t::payloadLength, print_addr_dec(), safe_exit(), message_t::src, message_t::src_port, TFTP_DEFAULT_FILENAME, TFTP_OPCODE_WRQ_SINGLE, TFTP_SINGLE_BLOCK_WAIT_TIME, timers_create_timer(), and udp_get_localhost_ip().
Referenced by main().
void tftp_setStatus (uint8_t newStatus)
Definition at line 45 of file tftp.c.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_initialize(), tftp_sendRequest(), and TIMER_HANDLER_FUNCTION().
uint16_t tftp_transfer_dst_port (void)
Definition at line 53 of file tftp.c.
uint16_t tftp_transfer_src_port (void)
Definition at line 49 of file tftp.c.
Referenced by udp_packet_demultiplexer().
TIMER_HANDLER_FUNCTION_PROTO (tftp_timer_handler)