KthWsnLongrangeRadioUplink: timers.c File Reference
timers.c File Reference
#include <signal.h>
#include <sys/time.h>
#include <stdio.h>
#include <string.h>
#include "timers.h"
Functions
uint8_t timers_initialize (void(*handlerfptr)(int sig))
uint8_t timers_create_timer (int expireS, int intervalS, int expireUS, int intervalUS)
uint8_t timers_cancel_timer (void)
Variables
void(* mainTimerHandler)(int sig)
Function Documentation
uint8_t timers_cancel_timer (void)
Definition at line 67 of file timers.c.
References mainTimerHandler.
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t timers_create_timer (int expireS, int intervalS, int expireUS, int intervalUS)
Definition at line 19 of file timers.c.
References mainTimerHandler.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_sendData(), tftp_sendRequest(), tftp_sendSingleBlockData(), and TIMER_HANDLER_FUNCTION().
uint8_t timers_initialize (void(*)(int sig) handlerfptr)
Definition at line 13 of file timers.c.
References mainTimerHandler.
Referenced by main().
Variable Documentation
void(* mainTimerHandler)(int sig)
Definition at line 11 of file timers.c.
Referenced by timers_cancel_timer(), timers_create_timer(), and timers_initialize().