KthWsnLongrangeRadioUplink: Header Files/timers.h File Reference
Header Files/timers.h File Reference
#include <signal.h>
#include <time.h>
#include <stdio.h>
#include <inttypes.h>
#include <stdint.h>
Defines
#define TIMER_HANDLER_FUNCTION_PROTO(timerHandler) uint8_t timerHandler()
#define TIMER_HANDLER_FUNCTION(timerHandler) uint8_t timerHandler()
Typedefs
typedef uint8_t(* timerHandlerfptr_t)(void)
Functions
uint8_t timers_initialize (void(*handlerfptr)(int sig))
uint8_t timers_create_timer (int expireS, int intervalS, int expireUS, int intervalUS)
uint8_t timers_cancel_timer (void)
Define Documentation
#define TIMER_HANDLER_FUNCTION (timerHandler) uint8_t timerHandler()
Definition at line 22 of file timers.h.
#define TIMER_HANDLER_FUNCTION_PROTO (timerHandler) uint8_t timerHandler()
Definition at line 21 of file timers.h.
Typedef Documentation
typedef uint8_t(* timerHandlerfptr_t)(void)
Definition at line 24 of file timers.h.
Function Documentation
uint8_t timers_cancel_timer (void)
Definition at line 67 of file timers.c.
References mainTimerHandler.
Referenced by PACKET_HANDLER_FUNCTION().
uint8_t timers_create_timer (int expireS, int intervalS, int expireUS, int intervalUS)
Definition at line 19 of file timers.c.
References mainTimerHandler.
Referenced by PACKET_HANDLER_FUNCTION(), tftp_sendData(), tftp_sendRequest(), tftp_sendSingleBlockData(), and TIMER_HANDLER_FUNCTION().
uint8_t timers_initialize (void(*)(int sig) handlerfptr)
Definition at line 13 of file timers.c.
References mainTimerHandler.
Referenced by main().