KthWsnLongrangeRadioUplink: udp_ip.c File Reference
udp_ip.c File Reference
#include <stdio.h>
#include <inttypes.h>
#include <stdint.h>
#include <string.h>
#include "udp_ip.h"
Functions
dataQueuerfptr_t udp_get_data_queuer_fptr (void)
void udp_initialize_ip_network (uint8_t *myIpAddress, dataQueuerfptr_t dataQueuer)
uint8_t * udp_get_localhost_ip (uint8_t *ip_out)
uint8_t * udp_get_broadcast_ip (uint8_t *ip_out)
uint16_t udp_create_packet (uint8_t *src_in, uint16_t src_port, uint8_t *dst_in, uint16_t dst_port, uint8_t *payload_in, uint16_t payload_length, uint8_t *packet_out)
uint8_t udp_check_destination (uint8_t *my_dst, uint8_t *packet_dst, uint8_t *packet_in)
uint16_t udp_open_packet_extended (uint8_t *src_out, uint16_t *src_port_out, uint8_t *dst_out, uint16_t *dst_port_out, uint8_t *payload_out, uint8_t *packet_in, uint8_t *flow_label_out, uint8_t *hop_limit_out, uint8_t *next_header_out, uint8_t *version_out, uint8_t *priority_out)
uint16_t udp_open_packet (uint8_t *src_out, uint16_t *src_port_out, uint8_t *dst_out, uint16_t *dst_port_out, uint8_t *payload_out, uint8_t *packet_in)
Function Documentation
uint8_t udp_check_destination (uint8_t * my_dst, uint8_t * packet_dst, uint8_t * packet_in)
Definition at line 175 of file udp_ip.c.
References IPV6_DESTINATION_LENGTH, and IPV6_DESTINATION_OFFSET.
uint16_t udp_create_packet (uint8_t * src_in, uint16_t src_port, uint8_t * dst_in, uint16_t dst_port, uint8_t * payload_in, uint16_t payload_length, uint8_t * packet_out)
Definition at line 97 of file udp_ip.c.
References IPV6_DESTINATION_LENGTH, IPV6_DESTINATION_OFFSET, IPV6_FLOW_LABEL_LENGTH, IPV6_FLOW_LABEL_OFFSET, IPV6_HOP_LIMIT, IPV6_HOP_LIMIT_LENGTH, IPV6_HOP_LIMIT_OFFSET, IPV6_NEXT_HEADER_LENGTH, IPV6_NEXT_HEADER_OFFSET, IPV6_PAYLOAD_LENGTH_LENGTH, IPV6_PAYLOAD_LENGTH_OFFSET, IPV6_SOURCE_LENGTH, IPV6_SOURCE_OFFSET, IPV6_VERSION_PRIORITY_LENGTH, IPV6_VERSION_PRIORITY_OFFSET, UDP_CHECKSUM_LENGTH, UDP_CHECKSUM_OFFSET, UDP_DESTINATION_PORT_LENGTH, UDP_DESTINATION_PORT_OFFSET, UDP_LENGTH_LENGTH, UDP_LENGTH_OFFSET, UDP_MAX_PAYLOAD_LENGTH, UDP_PAYLOAD_OFFSET, UDP_SOURCE_PORT_LENGTH, and UDP_SOURCE_PORT_OFFSET.
Referenced by queueSerialData().
uint8_t* udp_get_broadcast_ip (uint8_t * ip_out)
Definition at line 85 of file udp_ip.c.
Referenced by main(), and udp_packet_demultiplexer().
dataQueuerfptr_t udp_get_data_queuer_fptr (void)
Definition at line 60 of file udp_ip.c.
Referenced by main().
uint8_t* udp_get_localhost_ip (uint8_t * ip_out)
Definition at line 74 of file udp_ip.c.
Referenced by main(), tftp_sendAck(), tftp_sendData(), tftp_sendError(), tftp_sendRequest(), tftp_sendSingleBlockData(), TIMER_HANDLER_FUNCTION(), and udp_packet_demultiplexer().
void udp_initialize_ip_network (uint8_t * myIpAddress, dataQueuerfptr_t dataQueuer)
Definition at line 65 of file udp_ip.c.
Referenced by main().
uint16_t udp_open_packet (uint8_t * src_out, uint16_t * src_port_out, uint8_t * dst_out, uint16_t * dst_port_out, uint8_t * payload_out, uint8_t * packet_in)
Definition at line 282 of file udp_ip.c.
References udp_open_packet_extended().
Referenced by main().
uint16_t udp_open_packet_extended (uint8_t * src_out, uint16_t * src_port_out, uint8_t * dst_out, uint16_t * dst_port_out, uint8_t * payload_out, uint8_t * packet_in, uint8_t * flow_label_out, uint8_t * hop_limit_out, uint8_t * next_header_out, uint8_t * version_out, uint8_t * priority_out)
Definition at line 194 of file udp_ip.c.
References IPV6_DESTINATION_LENGTH, IPV6_DESTINATION_OFFSET, IPV6_FLOW_LABEL_LENGTH, IPV6_FLOW_LABEL_OFFSET, IPV6_HOP_LIMIT_LENGTH, IPV6_HOP_LIMIT_OFFSET, IPV6_NEXT_HEADER_LENGTH, IPV6_NEXT_HEADER_OFFSET, IPV6_PAYLOAD_LENGTH_OFFSET, IPV6_SOURCE_LENGTH, IPV6_SOURCE_OFFSET, IPV6_VERSION_PRIORITY_OFFSET, UDP_CHECKSUM_OFFSET, UDP_DESTINATION_PORT_OFFSET, UDP_LENGTH_OFFSET, UDP_PAYLOAD_OFFSET, and UDP_SOURCE_PORT_OFFSET.
Referenced by udp_open_packet().